require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Exclude:
    - bin/update
    - bin/setup
    - bin/bundle
    - Guardfile
    - db/schema.rb

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/services/importer_service_spec.rb

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - spec/features/get_course_information_spec.rb

Style/Documentation:
  Exclude:
    - db/migrate/*

Style/Documentation:
  Enabled: false